# Generated by Django 6.0.4 on 2026-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'films',
            },
        ),
        migrations.DeleteModel(
            name='Films',
        ),
    ]
