# Generated by Django 6.0.1 on 2026-06-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-rating'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (мин)'),
        ),
        migrations.AddField(
            model_name='film',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='film',
            name='quality',
            field=models.CharField(choices=[('HD', 'HD'), ('Full HD', 'Full HD'), ('4K', '4K'), ('CAM', 'CAM')], default='HD', max_length=20, verbose_name='Качество'),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='От 0.0 до 10.0', max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(max_length=200, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
