# Generated by Django 6.0.5 on 2026-05-19 07:06

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_genre_alter_film_options_alter_film_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='title', unique_with=['year']),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='genre', unique=True),
        ),
        migrations.CreateModel(
            name='FilmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movies/', verbose_name='Изображение/Кадр')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='films.film', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Изображение фильма',
                'verbose_name_plural': 'Изображения фильма',
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время сеанса')),
                ('hall_name', models.CharField(max_length=50, verbose_name='Зал')),
                ('price', models.FloatField(verbose_name='Цена билета на этот сеанс')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(verbose_name='Место')),
                ('row_number', models.IntegerField(verbose_name='Ряд')),
                ('is_bought', models.BooleanField(default=False, verbose_name='Куплен')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.showtime', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'unique_together': {('showtime', 'row_number', 'seat_number')},
            },
        ),
    ]
