# Generated by Django 6.0.5 on 2026-06-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_film_slug'),
        ('films', '0007_promobanner'),
    ]

    operations = [
    ]
