# Generated by Django 6.0.5 on 2026-06-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_merge_0007_alter_film_slug_0007_promobanner'),
        ('films', '0008_replace_autoslug_with_slugfield'),
    ]

    operations = [
    ]
