# Generated by Django 6.0.5 on 2026-06-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_slideritem_banneritem_remove_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, null=True, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
